# Generated by Django 4.2.16 on 2024-10-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, unique=True)),
                ('longitube', models.DecimalField(decimal_places=8, max_digits=10, unique=True)),
                ('height', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LevelPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2А', '2Б'), ('2А', '2Б'), ('3А', '3Б'), ('3Б', '3Б')], default='1А', max_length=2)),
                ('summer_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2А', '2Б'), ('2А', '2Б'), ('3А', '3Б'), ('3Б', '3Б')], default='1А', max_length=2)),
                ('spring_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2А', '2Б'), ('2А', '2Б'), ('3А', '3Б'), ('3Б', '3Б')], default='1А', max_length=2)),
                ('autumn_level', models.CharField(choices=[('1A', '1A'), ('1Б', '1Б'), ('2А', '2Б'), ('2А', '2Б'), ('3А', '3Б'), ('3Б', '3Б')], default='1А', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glory_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('other_titles', models.CharField(max_length=300, unique=True)),
                ('connect', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'NEW'), ('AC', 'ACCEPTED'), ('PD', 'PENDING'), ('RJ', 'REJECTED')], default='NW', max_length=5)),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ground.coord')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground.levelpoint')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ground.image')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ground.user')),
            ],
        ),
    ]
